-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.barrios
(
    ogc_fid serial NOT NULL,
    wkb_geometry geometry(MultiPolygon,32619),
    fid numeric(9, 0),
    objectid double precision,
    prov character varying(254) COLLATE pg_catalog."default",
    mun character varying(254) COLLATE pg_catalog."default",
    dm character varying(254) COLLATE pg_catalog."default",
    secc character varying(254) COLLATE pg_catalog."default",
    bp character varying(254) COLLATE pg_catalog."default",
    bp_area_km numeric(33, 15),
    toponimia character varying(254) COLLATE pg_catalog."default",
    enlace character varying(254) COLLATE pg_catalog."default",
    topo2 character varying(254) COLLATE pg_catalog."default",
    rup character varying(254) COLLATE pg_catalog."default",
    area_m2 double precision,
    CONSTRAINT barrios_pk PRIMARY KEY (ogc_fid)
);

CREATE TABLE IF NOT EXISTS public.distritos
(
    ogc_fid serial NOT NULL,
    wkb_geometry geometry(MultiPolygon,32619),
    fid numeric(9, 0),
    prov character varying(254) COLLATE pg_catalog."default",
    mun character varying(254) COLLATE pg_catalog."default",
    dm character varying(254) COLLATE pg_catalog."default",
    toponimia character varying(254) COLLATE pg_catalog."default",
    reg character varying(254) COLLATE pg_catalog."default",
    km2 numeric(33, 15),
    enlace character varying(254) COLLATE pg_catalog."default",
    topo2 character varying(254) COLLATE pg_catalog."default",
    rup character varying(254) COLLATE pg_catalog."default",
    area_m2 double precision,
    CONSTRAINT distritos_pk PRIMARY KEY (ogc_fid)
);

CREATE TABLE IF NOT EXISTS public.distritos_ref
(
    id serial NOT NULL,
    dm character varying(254) COLLATE pg_catalog."default",
    CONSTRAINT distritos_ref_pkey PRIMARY KEY (id),
    CONSTRAINT distritos_ref_dm_key UNIQUE (dm)
);

CREATE TABLE IF NOT EXISTS public.hospitales
(
    ogc_fid integer NOT NULL DEFAULT nextval('barrios_ogc_fid_seq'::regclass),
    nombre character varying COLLATE pg_catalog."default",
    direccion character varying COLLATE pg_catalog."default",
    tipo_de_centro character varying COLLATE pg_catalog."default",
    regional_de_la_salud character varying COLLATE pg_catalog."default",
    provincia_toponimia character varying COLLATE pg_catalog."default",
    prov character varying COLLATE pg_catalog."default",
    municipio_toponimia character varying COLLATE pg_catalog."default",
    mun character varying COLLATE pg_catalog."default",
    sector_toponimia character varying COLLATE pg_catalog."default",
    lat numeric NOT NULL,
    lon numeric NOT NULL,
    ubicacion geometry(Point,4326),
    dm character varying COLLATE pg_catalog."default",
    CONSTRAINT hospitales_pkey PRIMARY KEY (ogc_fid)
);

CREATE TABLE IF NOT EXISTS public.municipios
(
    ogc_fid serial NOT NULL,
    wkb_geometry geometry(MultiPolygon,32619),
    fid numeric(9, 0),
    prov character varying(254) COLLATE pg_catalog."default",
    mun character varying(254) COLLATE pg_catalog."default",
    reg character varying(254) COLLATE pg_catalog."default",
    toponimia character varying(254) COLLATE pg_catalog."default",
    "KM2" numeric(33, 15),
    "ENLACE" character varying(254) COLLATE pg_catalog."default",
    "TOPO2" character varying(254) COLLATE pg_catalog."default",
    "RUP" character varying(254) COLLATE pg_catalog."default",
    area_m2 double precision,
    CONSTRAINT municipios_pk PRIMARY KEY (ogc_fid)
);

CREATE TABLE IF NOT EXISTS public.municipios_ref
(
    id serial NOT NULL,
    mun character varying(254) COLLATE pg_catalog."default",
    CONSTRAINT municipios_ref_pkey PRIMARY KEY (id),
    CONSTRAINT municipios_ref_mun_key UNIQUE (mun)
);

CREATE TABLE IF NOT EXISTS public.provincias
(
    ogc_fid integer NOT NULL DEFAULT nextval('provinciasdump_ogc_fid_seq'::regclass),
    wkb_geometry geometry(MultiPolygon,32619),
    fid numeric(9, 0),
    prov character varying(254) COLLATE pg_catalog."default",
    toponimia character varying(254) COLLATE pg_catalog."default",
    reg character varying(254) COLLATE pg_catalog."default",
    km2 numeric(33, 15),
    rup character varying(254) COLLATE pg_catalog."default",
    CONSTRAINT provinciasdump_pk PRIMARY KEY (ogc_fid)
);

CREATE TABLE IF NOT EXISTS public.provincias_ref
(
    id serial NOT NULL,
    prov character varying(254) COLLATE pg_catalog."default",
    CONSTRAINT provincias_ref_pkey PRIMARY KEY (id),
    CONSTRAINT provincias_ref_prov_key UNIQUE (prov)
);

CREATE TABLE IF NOT EXISTS public.secciones
(
    ogc_fid serial NOT NULL,
    wkb_geometry geometry(MultiPolygon,32619),
    fid numeric(9, 0),
    reg character varying(254) COLLATE pg_catalog."default",
    prov character varying(254) COLLATE pg_catalog."default",
    mun character varying(254) COLLATE pg_catalog."default",
    sec character varying(254) COLLATE pg_catalog."default",
    dm character varying(254) COLLATE pg_catalog."default",
    toponimia character varying(254) COLLATE pg_catalog."default",
    km2 character varying(254) COLLATE pg_catalog."default",
    enlace character varying(254) COLLATE pg_catalog."default",
    rup character varying(254) COLLATE pg_catalog."default",
    topo2 character varying(254) COLLATE pg_catalog."default",
    area_m2 double precision,
    CONSTRAINT secciones_pk PRIMARY KEY (ogc_fid)
);

CREATE TABLE IF NOT EXISTS public.secciones_ref
(
    id serial NOT NULL,
    secc character varying(254) COLLATE pg_catalog."default",
    CONSTRAINT secciones_ref_pkey PRIMARY KEY (id),
    CONSTRAINT secciones_ref_secc_key UNIQUE (secc)
);

ALTER TABLE IF EXISTS public.barrios
    ADD CONSTRAINT fk_barrios_dm FOREIGN KEY (dm)
    REFERENCES public.distritos_ref (dm) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.barrios
    ADD CONSTRAINT fk_barrios_mun FOREIGN KEY (mun)
    REFERENCES public.municipios_ref (mun) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.barrios
    ADD CONSTRAINT fk_barrios_prov FOREIGN KEY (prov)
    REFERENCES public.provincias_ref (prov) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.barrios
    ADD CONSTRAINT fk_barrios_secc FOREIGN KEY (secc)
    REFERENCES public.secciones_ref (secc) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.distritos
    ADD CONSTRAINT fk_distritos_mun FOREIGN KEY (mun)
    REFERENCES public.municipios_ref (mun) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.distritos
    ADD CONSTRAINT fk_distritos_prov FOREIGN KEY (prov)
    REFERENCES public.provincias_ref (prov) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.hospitales
    ADD CONSTRAINT fk_hospitales_dm FOREIGN KEY (dm)
    REFERENCES public.distritos_ref (dm) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.hospitales
    ADD CONSTRAINT fk_hospitales_mun FOREIGN KEY (mun)
    REFERENCES public.municipios_ref (mun) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.hospitales
    ADD CONSTRAINT fk_hospitales_prov FOREIGN KEY (prov)
    REFERENCES public.provincias_ref (prov) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.municipios
    ADD CONSTRAINT fk_municipios_prov FOREIGN KEY (prov)
    REFERENCES public.provincias_ref (prov) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.secciones
    ADD CONSTRAINT fk_secciones_dm FOREIGN KEY (dm)
    REFERENCES public.distritos_ref (dm) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.secciones
    ADD CONSTRAINT fk_secciones_mun FOREIGN KEY (mun)
    REFERENCES public.municipios_ref (mun) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.secciones
    ADD CONSTRAINT fk_secciones_prov FOREIGN KEY (prov)
    REFERENCES public.provincias_ref (prov) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;